name: Fetch Excel Data

on:
  workflow_dispatch:
    inputs:
      filename:
        description : "Enter the Excel File Name (with extension)"
        required: true
        default: "Int B.Tech_M.tech.xslx" 
      row_number:
        description: "Enter the Excel row nuber to fetch"
        required: true
        default: "2"

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Run Python script
        run: |
          python workflows/fetch_data.py "${{ github.event.inputs.filename }}" "${{ github.event.inputs.row_number }}"
